# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# Spring配置
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/activiti_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: 123456

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.221:3306/Ruoyi_activiti?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: db!23456
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true

  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB

  activiti:
    check-process-definitions: false
    database-schema-update: true
    history-level: full
    db-history-used: true
    serialize-p-o-j-os-in-variables-to-json: false
    #禁用懒加载:
    async-executor-activate: false
  main:
    allow-bean-definition-overriding: true


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false
  # 请求前缀
  pathMapping: /dev-api

